import { DrawingGuessPrompt } from './types';

export const drawingGuessWordBank: DrawingGuessPrompt[] = [
  {
    id: 'apple',
    text: 'Apple',
    category: 'food',
    aliases: ['تفاحة', 'تفاح'],
  },
  {
    id: 'coffee-cup',
    text: 'Coffee cup',
    category: 'objects',
    aliases: ['قهوة', 'كوب قهوة', 'فنجان'],
  },
  {
    id: 'house',
    text: 'House',
    category: 'household',
    aliases: ['بيت', 'منزل', 'دار'],
  },
  {
    id: 'airport',
    text: 'Airport',
    category: 'places',
    aliases: ['مطار'],
  },
  {
    id: 'running',
    text: 'Running',
    category: 'actions',
    aliases: ['ركض', 'جري', 'يركض'],
  },
  {
    id: 'cat',
    text: 'Cat',
    category: 'animals',
    aliases: ['قطة', 'قط', 'بسة'],
  },
  {
    id: 'key',
    text: 'Key',
    category: 'objects',
    aliases: ['مفتاح'],
  },
  {
    id: 'pizza',
    text: 'Pizza',
    category: 'food',
    aliases: ['بيتزا'],
  },
  {
    id: 'banana',
    text: 'Banana',
    category: 'food',
    aliases: ['موز', 'موزه'],
  },
  {
    id: 'burger',
    text: 'Burger',
    category: 'food',
    aliases: ['برغر', 'برجر', 'همبرغر'],
  },
  {
    id: 'ice-cream',
    text: 'Ice cream',
    category: 'food',
    aliases: ['آيس كريم', 'ايس كريم', 'مثلجات'],
  },
  {
    id: 'cake',
    text: 'Cake',
    category: 'food',
    aliases: ['كيك', 'كعكة', 'كيكة'],
  },
  {
    id: 'bread',
    text: 'Bread',
    category: 'food',
    aliases: ['خبز', 'رغيف'],
  },
  {
    id: 'watermelon',
    text: 'Watermelon',
    category: 'food',
    aliases: ['بطيخ', 'رقي'],
  },
  {
    id: 'fish',
    text: 'Fish',
    category: 'food',
    aliases: ['سمكة', 'سمك'],
  },
  {
    id: 'egg',
    text: 'Egg',
    category: 'food',
    aliases: ['بيضة', 'بيض'],
  },
  {
    id: 'donut',
    text: 'Donut',
    category: 'food',
    aliases: ['دونات', 'كعكة دائرية'],
  },
  {
    id: 'phone',
    text: 'Phone',
    category: 'objects',
    aliases: ['هاتف', 'موبايل', 'جوال'],
  },
  {
    id: 'book',
    text: 'Book',
    category: 'objects',
    aliases: ['كتاب', 'دفتر'],
  },
  {
    id: 'chair',
    text: 'Chair',
    category: 'objects',
    aliases: ['كرسي'],
  },
  {
    id: 'car',
    text: 'Car',
    category: 'objects',
    aliases: ['سيارة', 'عربة'],
  },
  {
    id: 'bicycle',
    text: 'Bicycle',
    category: 'objects',
    aliases: ['دراجة', 'بايسكل'],
  },
  {
    id: 'umbrella',
    text: 'Umbrella',
    category: 'objects',
    aliases: ['مظلة', 'شمسية'],
  },
  {
    id: 'clock',
    text: 'Clock',
    category: 'objects',
    aliases: ['ساعة', 'ساعة حائط'],
  },
  {
    id: 'glasses',
    text: 'Glasses',
    category: 'objects',
    aliases: ['نظارات', 'نظارة'],
  },
  {
    id: 'backpack',
    text: 'Backpack',
    category: 'objects',
    aliases: ['حقيبة', 'حقيبة ظهر', 'جنطة'],
  },
  {
    id: 'ball',
    text: 'Ball',
    category: 'objects',
    aliases: ['كرة', 'طابة'],
  },
  {
    id: 'school',
    text: 'School',
    category: 'places',
    aliases: ['مدرسة'],
  },
  {
    id: 'park',
    text: 'Park',
    category: 'places',
    aliases: ['حديقة', 'منتزه'],
  },
  {
    id: 'beach',
    text: 'Beach',
    category: 'places',
    aliases: ['شاطئ', 'بحر'],
  },
  {
    id: 'hospital',
    text: 'Hospital',
    category: 'places',
    aliases: ['مستشفى'],
  },
  {
    id: 'restaurant',
    text: 'Restaurant',
    category: 'places',
    aliases: ['مطعم'],
  },
  {
    id: 'market',
    text: 'Market',
    category: 'places',
    aliases: ['سوق', 'محل'],
  },
  {
    id: 'bridge',
    text: 'Bridge',
    category: 'places',
    aliases: ['جسر', 'كوبري'],
  },
  {
    id: 'farm',
    text: 'Farm',
    category: 'places',
    aliases: ['مزرعة', 'حقل'],
  },
  {
    id: 'library',
    text: 'Library',
    category: 'places',
    aliases: ['مكتبة'],
  },
  {
    id: 'zoo',
    text: 'Zoo',
    category: 'places',
    aliases: ['حديقة حيوان'],
  },
  {
    id: 'jumping',
    text: 'Jumping',
    category: 'actions',
    aliases: ['قفز', 'يقفز'],
  },
  {
    id: 'swimming',
    text: 'Swimming',
    category: 'actions',
    aliases: ['سباحة', 'يسبح'],
  },
  {
    id: 'dancing',
    text: 'Dancing',
    category: 'actions',
    aliases: ['رقص', 'يرقص'],
  },
  {
    id: 'sleeping',
    text: 'Sleeping',
    category: 'actions',
    aliases: ['نوم', 'نائم', 'ينام'],
  },
  {
    id: 'cooking',
    text: 'Cooking',
    category: 'actions',
    aliases: ['طبخ', 'يطبخ'],
  },
  {
    id: 'reading',
    text: 'Reading',
    category: 'actions',
    aliases: ['قراءة', 'يقرأ'],
  },
  {
    id: 'singing',
    text: 'Singing',
    category: 'actions',
    aliases: ['غناء', 'يغني'],
  },
  {
    id: 'painting',
    text: 'Painting',
    category: 'actions',
    aliases: ['رسم', 'يرسم', 'تلوين'],
  },
  {
    id: 'brushing-teeth',
    text: 'Brushing teeth',
    category: 'actions',
    aliases: ['تنظيف الأسنان', 'يفرش أسنانه'],
  },
  {
    id: 'flying-kite',
    text: 'Flying a kite',
    category: 'actions',
    aliases: ['طائرة ورقية', 'يطير طائرة ورقية'],
  },
  {
    id: 'dog',
    text: 'Dog',
    category: 'animals',
    aliases: ['كلب'],
  },
  {
    id: 'bird',
    text: 'Bird',
    category: 'animals',
    aliases: ['طائر', 'عصفور'],
  },
  {
    id: 'horse',
    text: 'Horse',
    category: 'animals',
    aliases: ['حصان', 'خيل'],
  },
  {
    id: 'cow',
    text: 'Cow',
    category: 'animals',
    aliases: ['بقرة'],
  },
  {
    id: 'rabbit',
    text: 'Rabbit',
    category: 'animals',
    aliases: ['أرنب', 'ارنب'],
  },
  {
    id: 'lion',
    text: 'Lion',
    category: 'animals',
    aliases: ['أسد', 'اسد'],
  },
  {
    id: 'elephant',
    text: 'Elephant',
    category: 'animals',
    aliases: ['فيل'],
  },
  {
    id: 'turtle',
    text: 'Turtle',
    category: 'animals',
    aliases: ['سلحفاة'],
  },
  {
    id: 'duck',
    text: 'Duck',
    category: 'animals',
    aliases: ['بطة', 'بط'],
  },
  {
    id: 'bee',
    text: 'Bee',
    category: 'animals',
    aliases: ['نحلة'],
  },
  {
    id: 'bed',
    text: 'Bed',
    category: 'household',
    aliases: ['سرير', 'فراش'],
  },
  {
    id: 'lamp',
    text: 'Lamp',
    category: 'household',
    aliases: ['مصباح', 'لمبة'],
  },
  {
    id: 'sofa',
    text: 'Sofa',
    category: 'household',
    aliases: ['أريكة', 'كنبة', 'صوفة'],
  },
  {
    id: 'table',
    text: 'Table',
    category: 'household',
    aliases: ['طاولة', 'منضدة'],
  },
  {
    id: 'mirror',
    text: 'Mirror',
    category: 'household',
    aliases: ['مرآة', 'مراية'],
  },
  {
    id: 'television',
    text: 'Television',
    category: 'household',
    aliases: ['تلفاز', 'تلفزيون', 'شاشة'],
  },
  {
    id: 'door',
    text: 'Door',
    category: 'household',
    aliases: ['باب'],
  },
  {
    id: 'window',
    text: 'Window',
    category: 'household',
    aliases: ['نافذة', 'شباك'],
  },
  {
    id: 'pillow',
    text: 'Pillow',
    category: 'household',
    aliases: ['وسادة', 'مخدة'],
  },
  {
    id: 'toothbrush',
    text: 'Toothbrush',
    category: 'household',
    aliases: ['فرشاة أسنان', 'فرشة أسنان'],
  },
];

export const getPromptById = (promptId: string) =>
  drawingGuessWordBank.find((prompt) => prompt.id === promptId);

export const drawingGuessPromptCategoryLabels = {
  objects: 'Object',
  food: 'Food',
  places: 'Place',
  actions: 'Action',
  animals: 'Animal',
  household: 'Home',
} as const satisfies Record<DrawingGuessPrompt['category'], string>;
