import { AdminStoreCatalogItem } from './adminDashboardApi';

export default function StoreCatalogTable({ items, onDuplicate, onEdit, onInspect }: { items: AdminStoreCatalogItem[]; onDuplicate?: (item: AdminStoreCatalogItem) => void; onEdit?: (item: AdminStoreCatalogItem) => void; onInspect: (item: AdminStoreCatalogItem) => void }) {
  return <div className="economy-table-wrap"><table className="economy-table"><thead><tr><th>العنصر</th><th>القسم</th><th>السعر</th><th>المدة</th><th>المخزون</th><th>حالة البيع</th><th>الترتيب</th><th>آخر تعديل</th><th /></tr></thead><tbody>{items.map((item) => <tr key={item.itemId}><td><button className="economy-item" onClick={() => onInspect(item)} type="button"><img alt="" src={item.thumbnailUrl} /><span><strong>{item.name.ar}</strong><small dir="ltr">{item.itemId}</small></span></button></td><td>{categoryLabel(item.category)}</td><td><Price prices={item.prices} /></td><td>{durationLabel(item.duration)}</td><td>{item.stock.kind === 'unlimited' ? 'غير محدود' : item.stock.remaining.toLocaleString('ar-IQ')}</td><td><div className="economy-state-stack"><Status value={item.availability} /><small className={item.purchasingEnabled ? 'sale-enabled' : 'sale-disabled'}>{item.purchasingEnabled ? 'الشراء مفعّل' : 'الشراء متوقف'}</small></div></td><td>#{item.order.toLocaleString('ar-IQ')}</td><td><span>{relativeTime(item.updatedAt)}</span><small dir="ltr">{item.lastEditorEmail || '—'}</small></td><td><div className="economy-row-actions"><button className="economy-row-action subtle" onClick={() => onInspect(item)} type="button">الملف</button>{onEdit ? <button className="economy-row-action" onClick={() => onEdit(item)} type="button">تعديل</button> : null}{onDuplicate ? <button className="economy-row-action subtle" onClick={() => onDuplicate(item)} type="button">نسخ</button> : null}</div></td></tr>)}</tbody></table></div>;
}

function Price({ prices }: { prices: AdminStoreCatalogItem['prices'] }) { return <span className="economy-price">{prices.coins ? `${prices.coins.toLocaleString('ar-IQ')} ◈` : ''}{prices.coins && prices.diamonds ? ' · ' : ''}{prices.diamonds ? `${prices.diamonds.toLocaleString('ar-IQ')} ♦` : ''}</span>; }
function Status({ value }: { value: string }) { const labels: Record<string, string> = { available: 'متاح', disabled: 'متوقف', unavailable: 'غير متاح', sold: 'مباع' }; return <span className={`economy-status status-${value}`}>{labels[value] || value}</span>; }
function categoryLabel(value: AdminStoreCatalogItem['category']) { return ({ 'game-items': 'عناصر اللعبة', 'chat-themes': 'سمات الدردشة', 'avatar-frames': 'إطارات الصور', 'profile-skins': 'خلفيات الملف', 'chat-bubbles': 'فقاعات الدردشة', nameplates: 'لوحات الاسم', 'cosmetic-badges': 'الشارات التجميلية', 'seat-effects': 'تأثيرات المقعد', stickers: 'ملصقات الدردشة', cars: 'السيارات', 'custom-ids': 'معرّفات مخصصة' } as const)[value]; }
function durationLabel(value: AdminStoreCatalogItem['duration']) { return value.kind === 'permanent' ? 'دائم' : `${value.value.toLocaleString('ar-IQ')} ${value.unit === 'days' ? 'يوم' : value.unit === 'weeks' ? 'أسبوع' : 'شهر'}`; }
function relativeTime(value: string) { if (!value) return 'غير محدد'; const delta = Date.now() - Date.parse(value); if (!Number.isFinite(delta)) return 'غير محدد'; const minutes = Math.max(0, Math.floor(delta / 60000)); if (minutes < 1) return 'الآن'; if (minutes < 60) return `منذ ${minutes.toLocaleString('ar-IQ')} د`; const hours = Math.floor(minutes / 60); if (hours < 24) return `منذ ${hours.toLocaleString('ar-IQ')} س`; return `منذ ${Math.floor(hours / 24).toLocaleString('ar-IQ')} يوم`; }
