export type DirectChatLanguage = 'ar' | 'en';

const copy = {
  ar: {
    accept: 'قبول',
    all: 'الكل',
    archive: 'أرشفة',
    block: 'حظر',
    cancel: 'إلغاء',
    chats: 'المحادثات',
    chatsEyebrow: 'تواصل خاص وآمن',
    composeEmptyBody: 'أضف أصدقاء أولاً، أو اكتشف مستخدمين جدداً لبدء محادثة.',
    composeEmptyTitle: 'لا أصدقاء بعد',
    composeError: 'تعذر تحميل الأصدقاء',
    composeSearchA11y: 'البحث في الأصدقاء',
    composeSearchPlaceholder: 'ابحث عن صديق بالاسم',
    composeTitle: 'محادثة جديدة',
    conversations: 'المحادثات',
    discoverPeople: 'اكتشاف مستخدمين',
    draft: 'مسودة',
    emptyBody: 'اختر صديقاً من القائمة لبدء محادثة، أو اضغط محادثة جديدة.',
    emptyTitle: 'ابدأ أول محادثة',
    errorTitle: 'تعذر تحميل المحادثات',
    friends: 'الأصدقاء',
    friendsUnavailable: 'قائمة الأصدقاء غير متاحة حالياً.',
    loadingOlder: 'تحميل رسائل أقدم',
    mute: 'كتم',
    newChat: 'محادثة جديدة',
    noMessages: 'لا رسائل جديدة',
    noResults: 'لا توجد نتائج',
    image: 'صورة',
    offline: 'الاتصال غير مستقر — اضغط لإعادة المحاولة',
    requestNew: 'طلب جديد: ',
    requestSent: 'طلبك: ',
    requests: 'طلبات المحادثة',
    reviewRequests: 'مراجعة الطلبات',
    retry: 'إعادة المحاولة',
    safePrivate: 'المحادثة مرئية للمشاركين فقط، لكنها ليست مشفرة من طرف إلى طرف.',
    searchA11y: 'البحث في المحادثات والأصدقاء',
    searchPlaceholder: 'ابحث بالاسم',
    searchTryAgain: 'جرّب اسماً آخر.',
    startChat: 'اضغط لبدء محادثة',
    sticker: 'ملصق',
    unread: 'غير المقروءة',
    unavailableBody: 'ستظهر المحادثات هنا عند تفعيلها.',
    unavailableTitle: 'المحادثات غير مفعلة بعد',
    unmute: 'إلغاء الكتم',
    user: 'مستخدم',
    voiceNote: 'رسالة صوتية',
  },
  en: {
    accept: 'Accept',
    all: 'All',
    archive: 'Archive',
    block: 'Block',
    cancel: 'Cancel',
    chats: 'Chats',
    chatsEyebrow: 'Private, safer conversations',
    composeEmptyBody: 'Add friends first, or discover people to start a chat.',
    composeEmptyTitle: 'No friends yet',
    composeError: 'Could not load friends',
    composeSearchA11y: 'Search friends',
    composeSearchPlaceholder: 'Search friends by name',
    composeTitle: 'New chat',
    conversations: 'Conversations',
    discoverPeople: 'Discover people',
    draft: 'Draft',
    emptyBody: 'Pick a friend from the list to start a chat, or tap New chat.',
    emptyTitle: 'Start your first chat',
    errorTitle: 'Could not load chats',
    friends: 'Friends',
    friendsUnavailable: 'Friends list is unavailable right now.',
    loadingOlder: 'Load older messages',
    mute: 'Mute',
    newChat: 'New chat',
    noMessages: 'No new messages',
    noResults: 'No results',
    image: 'Photo',
    offline: 'Connection is unstable — tap to retry',
    requestNew: 'New request: ',
    requestSent: 'Your request: ',
    requests: 'Chat requests',
    reviewRequests: 'Review requests',
    retry: 'Try again',
    safePrivate: 'This chat is visible only to its participants, but it is not end-to-end encrypted.',
    searchA11y: 'Search chats and friends',
    searchPlaceholder: 'Search by name',
    searchTryAgain: 'Try another name.',
    startChat: 'Tap to start a chat',
    sticker: 'Sticker',
    unread: 'Unread',
    unavailableBody: 'Chats will appear here when this feature is enabled.',
    unavailableTitle: 'Chats are not enabled yet',
    unmute: 'Unmute',
    user: 'User',
    voiceNote: 'Voice message',
  },
} as const;

export function directChatCopy(language: DirectChatLanguage = 'ar') {
  return copy[language];
}
